llm_config:
  base_url: https://api.deepseek.com/
  api_key: xxxx
  model_name: deepseek-reasoner
  temperature: 0.7
  max_tokens: 8192
agent_config:
  max_iterations: 100
  max_retries: 3
  max_search_results: 10
mcp_config:
  mcpServers:
    amap-maps-streamableHTTP:
      transport: streamable_http
      enabled: true
      description: null
      env: null
      command: null
      args: null
      url: https://mcp.amap.com/mcp?key=00b05640cc55c0ba2b7f85e0b3f2e6e7
      headers: null
    jina-mcp-server:
      transport: streamable_http
      enabled: true
      description: null
      env: null
      command: null
      args: null
      url: https://mcp.jina.ai/v1
      headers:
        Authorization: Bearer jina_133c673d569840d3b1e379a526eee6d4VKMVBI9J5HYE2xd4ys7i6ehZUNb6
a2a_config:
  a2a_servers:
  - id: 8003772a-93a1-4a46-a433-be8afc9221b6
    base_url: https://example.com/a2a
    enabled: true
  - id: d021af39-ce72-4c25-8c4d-aab8d702958a
    base_url: https://example.com/a2a
    enabled: true
  - id: bd19ca75-35b3-4125-badf-4f14c4b814eb
    base_url: https://example.com/a2a
    enabled: true
  - id: 509bf7bc-9a29-426d-9bbe-b3eb5684fd7a
    base_url: https://example.com/a2a
    enabled: true
  - id: bf452e52-fe8a-4f6c-b489-f89df0185b36
    base_url: https://example.com/a2a
    enabled: true
  - id: bc38c007-707b-46c9-bfdc-7507291f0fc9
    base_url: https://example.com/a2a
    enabled: true
